name: status_saver
description: WhatsApp Status Saver and more

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^8.0.1
  path_provider: ^2.0.2
  chewie: ^1.2.1
  flutter_staggered_grid_view: ^0.4.0
  adaptive_theme: ^2.2.0
  fluttertoast: ^8.0.7
  video_thumbnail: ^0.3.3
  url_launcher: ^6.0.6
  country_pickers: ^2.0.0
  lottie: ^1.0.1
  share_plus: ^2.1.2
  in_app_review: ^2.0.2
  lint: ^1.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/animation/send.json

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica-Roman.ttf
        - asset: assets/fonts/Helvetica-Medium.ttf
          weight: 500
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700


